export const cardUrl: any = {
    'original': '../assets/poker.png',
    'AS': '../assets/AS.png',
    'AH': '../assets/AH.png',
    'AC': '../assets/AC.png',
    'AD': '../assets/AD.png',
    '2S': '../assets/2S.png',
    '2H': '../assets/2H.png',
    '2C': '../assets/2C.png',
    '2D': '../assets/2D.png',
    '3S': '../assets/3S.png',
    '3H': '../assets/3H.png',
    '3C': '../assets/3C.png',
    '3D': '../assets/3D.png',
    '4S': '../assets/4S.png',
    '4H': '../assets/4H.png',
    '4C': '../assets/4C.png',
    '4D': '../assets/4D.png',
    '5S': '../assets/5S.png',
    '5H': '../assets/5H.png',
    '5C': '../assets/5C.png',
    '5D': '../assets/5D.png',
    '6S': '../assets/6S.png',
    '6H': '../assets/6H.png',
    '6C': '../assets/6C.png',
    '6D': '../assets/6D.png',
    '7S': '../assets/7S.png',
    '7H': '../assets/7H.png',
    '7C': '../assets/7C.png',
    '7D': '../assets/7D.png',
    '8S': '../assets/8S.png',
    '8H': '../assets/8H.png',
    '8C': '../assets/8C.png',
    '8D': '../assets/8D.png',
    '9S': '../assets/9S.png',
    '9H': '../assets/9H.png',
    '9C': '../assets/9C.png',
    '9D': '../assets/9D.png',
    '10S': '../assets/10S.png',
    '10H': '../assets/10H.png',
    '10C': '../assets/10C.png',
    '10D': '../assets/10D.png',
    'JS': '../assets/JS.png',
    'JH': '../assets/JH.png',
    'JC': '../assets/JC.png',
    'JD': '../assets/JD.png',
    'QS': '../assets/QS.png',
    'QH': '../assets/QH.png',
    'QC': '../assets/QC.png',
    'QD': '../assets/QD.png',
    'KS': '../assets/KS.png',
    'KH': '../assets/KH.png',
    'KC': '../assets/KC.png',
    'KD': '../assets/KD.png',
}

export const pokemon: any[] = [
    'pikachu',
    'raquaza',
    'myself',
    'kyurem',
    'evee',
]
